stages:
  - build
  - release
  
pages-job:
  stage: build
  image: python:3.8
  pages:
    script:
      - pip install numpy pandas 
      - pip install setuptools
      - pip install sphinx
      - python setup.py build_sphinx
      - mv build/sphinx/html/ public/
    artifacts:
      paths:
      - public

release-job:
  stage: release
  image: python:3.8
  rules:
    - if: $CI_COMMIT_TAG ~= /^[0-9]+\.[0-9]+\.[0-9]+$/      # Run this job when a tag is like #.#.#
  release:
    name: '$CI_COMMIT_TAG'
    description: '$ CI_COMMIT_DESCRIPTION '
    tag_name: '$CI_COMMIT_TAG'                                       # elsewhere in the pipeline.
    ref: '$CI_COMMIT_TAG'
