workflow:
  # Run if tag is 0.00.00 indicating a release
  #     or pipeline ist started manually in gitlab
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_JOB_MANUAL == "true"

stages:
  - build
  - test
  - deploy

build_sdist:
  image: python:latest
  stage: build
  before_script:
    - pip install setuptools
  script:
    - python setup.py sdist
    - echo 'ls dist/*tar.gz'
    - ls dist/*tar.gz
    - echo 'cd dist && ls *tar.gz'
    - echo "$( cd dist && ls *tar.gz )"
    - echo "BUILD_VERSION=$( cd dist && ls *tar.gz )" >> build.env
    - echo "BUILD_JOB=${CI_JOB_ID}" >> build.env
  artifacts:
    paths:
      - dist
    reports:
      dotenv: build.env

build_pages:
  image: python:latest
  stage: build
  rules:
    - exists:
        - docs/conf.py
  script:
    - pip install setuptools
    - pip install sphinx sphinx-argparse
    - pip install numpy pandas
    - BUILDING_SPHINX=true sphinx-build -b html docs build/sphinx/html
    - mv build/sphinx/html/ public/
  artifacts:
    paths:
      - public

test_latest:
  image: python:latest
  stage: test
  script:
    - pip install pytest numpy pandas
    - pytest tests

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_sdist
      artifacts: true
    - job: test_latest
  rules:
    # Run this job when a tag is like #.#.#
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - echo building release
  release:
    name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_DESCRIPTION'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'

deploy_pypi:
  image: python:latest
  stage: deploy
  needs:
    - job: build_sdist
      artifacts: true
    - job: test_latest
  script:
    - pip install twine
    - twine check dist/*tar.gz
    - twine upload --repository-url https://upload.pypi.org/legacy/ --username __token__ --password $PYPI_ID_TOKEN dist/*tar.gz
