[global] 
command_packages=stdeb.command

[metadata]
name = readmet
version = attr: readmet.__version__
author = Clemens Drüe
author_email = druee@uni-trier.de
url = https://pypi.org/project/readmet/
description = Python library for reading and writing less popular formats used in meteorology.
long_description = file: README.md
long_description_content_type = text/markdown
keywords = meteorology, akterm, scintec-1, dmna, toa5
license = EUPL-1.2
classifiers =
    Topic :: Scientific/Engineering :: Atmospheric Science
    License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)
    Programming Language :: Python :: 3

[options]
packages = find:
zip_safe = True
include_package_data = True
install_requires =
    numpy
    pandas

[options.packages.find]
where = src
exclude = tests

[build_sphinx]
source-dir = docs
config-dir = docs
fresh-env = True
all-files = True
