#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__title__ = 'readmet'
__description__ = ('Python library for reading and writing '
                   'less popular formats used in meteorology.')
__url__ = 'https://github.com/cdruee/python-readmet'
__author__ = u'Clemens Drüe'
__author_email__ = 'druee@uni-trier.de'
__license__ = 'EUPL-1.2'
__copyright__ = '(C) 2019-2025 Clemens Drüe'

# __version__ is not hand-maintained here. readmet/_version.py is fully
# regenerated by setuptools_scm from the nearest git tag every time the
# package is built or `pip install -e .` is run (see [tool.setuptools_scm]
# in pyproject.toml) -- nothing persistent can survive in that file, which
# is exactly why it's kept separate from this one. The extra fallbacks
# below keep this importable even when the generated file is missing
# (e.g. a stray checkout that was never pip-installed/built).
try:
    from ._version import __version__
except ImportError:
    try:
        from importlib.metadata import version as _pkg_version
        __version__ = _pkg_version(__title__)
    except Exception:
        __version__ = '0.0.0.dev0+unknown'
